### ISSUE TITLE
Please hurry and upload the dataset, I can't wait any longer.

### ISSUE THREAD

**Issue by yt4766269** [DNA-Rendering/DNA-Rendering#1]
快点把数据集端上来把，我已经等不及了

**Comment by yt4766269** [comment]
![image](https://github.com/DNA-Rendering/DNA-Rendering/assets/13883222/ccf9e4ad-cd39-49a6-a3db-2a5dea0a4528)

**Comment by wywu** [comment]
https://dna-rendering.github.io/inner-download.html

**Comment by lbc402** [comment]
发邮件两天了，没有收到回复

**Comment by DNA-Rendering** [comment]
Thanks for your interest in our DNA-Rendering Dataset! We'll reply your request in every Wednesday and Friday. Thanks for your patience.
