### ISSUE TITLE
Where can I see the previews for each video along with their corresponding video IDs?

### ISSUE THREAD

**Issue by liwenssss** [DNA-Rendering/DNA-Rendering#10]
Hello, thank you for your excellent work. Since the dataset is too large, I would like to select only a few videos for experiment, but I cannot find where to see the previews of these videos.

**Comment by DNA-Rendering** [comment]
Hi @liwenssss ,

Thank you for your interest in DNA-Rendering dataset!

We've already uploaded the previews of data part 1 and data part 2 on the shared google drive link. You can find them in "Part */*_preview.zip".
