### ISSUE TITLE
How to batch download Google Cloud Drive datasets using scripts？

### ISSUE THREAD

**Issue by wenkaier** [DNA-Rendering/DNA-Rendering#13]

**Comment by DNA-Rendering** [comment]
Hi @wenkaier ,

Thank you for your interest in DNA-Rendering dataset!

We have uploaded **"*_file_gid".json** in each shared sub-folder. The file contains shared google files' name and id, which is helpful to batch download files. 

You could use [gdown](https://github.com/wkentaro/gdown) or any other libraries to download the files with the file id.
