### ISSUE TITLE
How to get access to a dataset

### ISSUE THREAD

**Issue by zzg-zzg** [DNA-Rendering/DNA-Rendering#14]
Dear Authors,

Approximately three weeks ago, I sent an email based on the instructions provided in the [link.](https://dna-rendering.github.io/inner-download.html) 
Unfortunately, my initial email received no response. Subsequently, I sent a follow-up email a few days ago (on Thursday), but I have still not received any reply.

If there are any additional materials required to access this data set, or if there are specific criteria or identity verification steps that I need to fulfill, I would greatly appreciate any further guidance or details you can provide.

Thank you very much for your time and assistance. I look forward to your response.

Best regards

**Comment by DNA-Rendering** [comment]
Dear @zzg-zzg ,

Thank you for your interest in DNA-Rendering dataset！

Your email had been marked as spam, therefore, we didn't see your email. We've already replied and shared the data link to you, please check it!
