### ISSUE TITLE
A-pose frames 

### ISSUE THREAD

**Issue by antonzub99** [DNA-Rendering/DNA-Rendering#15]
Thank you so much for releasing this gigantic data collection!

In the paper, you mentioned that all the actors were also captured in A-pose for a canonical model. However, the data that was released does not contain these frames. 

Could you let me know if you are planning to release this data, or maybe it is already there (though I didn't find A-poses in available sequences)? Canonical poses would be really helpful in many cases.

Thanks!

**Comment by DNA-Rendering** [comment]
Hi @antonzub99,

Thanks for your interest in the DNA-Rendering dataset! 

We'll share the A-pose data soon, please stay tuned!

**Comment by antonzub99** [comment]
Hello @DNA-Rendering,

thank you very much!

Are you by any chance planning to release tracked keypoints for A-poses and/or SMPLx annotations in the future?

**Comment by DNA-Rendering** [comment]
Hi @antonzub99 ,

We have plans to release the keypoints and SMPLx for A-pose data, but it won't be soon. 

If you're in a hurry, please check [xrmocap](https://github.com/openxrlab/xrmocap) to do detection by yourself.  

For the details, please refer to our paper and [this issue](https://github.com/DNA-Rendering/DNA-Rendering/issues/11).

**Comment by antonzub99** [comment]
I see, thanks a lot for the clarification! 
Closing the issue.
