### ISSUE TITLE
Suggest for other cloud download link

### ISSUE THREAD

**Issue by pengc02** [DNA-Rendering/DNA-Rendering#19]
<img width="1082" alt="fail" src="https://github.com/user-attachments/assets/719b886a-b43d-4140-b66f-c23070ecacde">
Thanks for your works! But now the google drive has a download limit and is hard to download loads of large files, i wish other formats of download links can be supported in the future!

**Comment by wchengad** [comment]
hi, @pengc02 you can forward the **replied** email by dna-rendering team to wchengad@connect.ust.hk to get the Baidu download link.

**Comment by DNA-Rendering** [comment]
plz send us an email to let us know your name (use the same email thread or reference your earlier application email) --we are working on an alternative cloud link, and once we have an organized version, we will reach out to you.

**Comment by pengc02** [comment]
> plz send us an email to let us know your name (use the same email thread or reference your earlier application email) --we are working on an alternative cloud link, and once we have an organized version, we will reach out to you.

Thanks very much, while i've finished the downloading.
