### ISSUE TITLE
How to use the camera parameters

### ISSUE THREAD

**Issue by John-Yao** [DNA-Rendering/DNA-Rendering#4]
Hi， Could you provide some demo for projecting joints generate by smplx parameters? 

I simply multiply smplx joints by color_camera['RT'] and project by  color_camera['K'] . The projects points is out of image

@DNA-Rendering @wywu  @simon3dv

**Comment by John-Yao** [comment]
By the way, the smplx is special for netural or male or female? And  I could not find gender infomation from rgb_smc.

**Comment by DNA-Rendering** [comment]
Hi John, 

Yes, we do provide scripts to visualize SMPLx parameters. Please check the **smc_visualization.py** file in dna_rendering_sample_code.zip in the shared google drive. We also provide **vis_smc_install.sh**  to help you install the correct environment and download necessary files.

The gender information is provided in main smc file, please use our provided smc reader to check .
