### ISSUE TITLE
smplx annotation is noisy

### ISSUE THREAD

**Issue by John-Yao** [DNA-Rendering/DNA-Rendering#5]
Hi, I visual vertices of smplx on image plane. The data is noisy

![018299CCE885C77E5A0A1697CBC3F52A](https://github.com/DNA-Rendering/DNA-Rendering/assets/22048231/3fa68a54-41f1-4d4e-89e8-6c4e8b8084cd)

Could you provide some demo about visualing vertices of smplx

**Comment by Lewis-lv0** [comment]
Greetings, sorry for being a bit off the topic. Did you download this dataset to the Linux server? I am using `gdown` and suffering from the daily download bandwidth. This is especially annoying with the folder download. Do you have any suggestions on it? Thanks.

**Comment by John-Yao** [comment]
@Lewis-lv0  The same situatation I met. and I downloaded these files manually!

**Comment by Lewis-lv0** [comment]
Hello and sorry to bother you again. Could you please share your code for visualizing vertices of smplx? I guess your result looks fine. 
@John-Yao

**Comment by John-Yao** [comment]
@Lewis-lv0
 I could not share my code public. The visual results seem noisy. Maybe there some bug in my code.
The  Visual pipepline is showed below: 
RT =  np.linalg.inv(color_camera['RT'])
pts3d = RT@vertices_homo
 and The pts3d project by color_camera['K'] .

**Comment by xiyichen** [comment]
Hi @John-Yao, I am also trying to visualize the SMPL fittings but there seems no clear instructions. How did you split the (55,3) "fullpose" into global orientation, body pose, hand pose, etc.?

**Comment by xiyichen** [comment]
![000009](https://github.com/DNA-Rendering/DNA-Rendering/assets/50854238/5bb2da54-fe4b-4ad1-b1ae-9c25c36a3ede)
Using the provided "smc_visualization.py", the mesh is indeed not aligned very well with the body in same frames, probably due to the error in smplify-x

**Comment by xiyichen** [comment]
@John-Yao Could you share your code for visualization? I think it should be bug-free. I used the opencv camera parameters and SMPL vertices but somehow couldn't localize it correctly in the 2d space

**Comment by DNA-Rendering** [comment]
Hi all, 

We updated some noisy SMPLx parameters in Oct 28th, 2023. Please re-download them, sorry for the inconvenience. 

For SMPLx visualization problems, please check [issue 4](https://github.com/DNA-Rendering/DNA-Rendering/issues/4#issuecomment-1783670863 ).
