### ISSUE TITLE
Annotations for part 2

### ISSUE THREAD

**Issue by xiyichen** [DNA-Rendering/DNA-Rendering#6]
Has annotations (smpl parameters, masks, etc.) for part 2 been released? On the timeline it seems that it has been released, but I can't find the file in the download link.
![image](https://github.com/DNA-Rendering/DNA-Rendering/assets/50854238/99a8ba11-e92c-484e-9ef0-0aaaa801d74e)

**Comment by DNA-Rendering** [comment]
Hi Xiyi,

Thanks for your interest on DNA-Rendering dataset! Sorry for the delay, we release annotations for part 2 on Oct 28th, 2023. Please check the shared google link.
