### ISSUE TITLE
Questions for 'Color_Calibration' in Camera Parameter

### ISSUE THREAD

**Issue by ShunyuanZheng** [DNA-Rendering/DNA-Rendering#8]
Hi, 

I found there exists a severe color difference among 5MP camera data, and how can I use the Color_Calibration parameters to revise it?

The parameters look different from a general Color Correction Matrix, thus directly multiplied with BGR value looks incorrect.

**Comment by DNA-Rendering** [comment]
Hi @ShunyuanZheng ,

Thank you for your interest in DNA-Rendering.  Please try to use the following codes to calibrate the provided color images.

```
def img_calib(img_bgr, bgr_calib):
    rs = []
    for i in range(3):
        channel = np.array(img_bgr[:,:,i],dtype=np.double)
        X = np.stack([channel**2,channel ,np.ones_like(channel)])
        y = np.dot(bgr_calib[i].reshape(1,3),X.reshape(3,-1)).reshape(channel.shape)
        rs.append(y)
    rs_img = np.stack(rs,axis=2)
    rs_i = cv2.normalize(rs_img, None, alpha=rs_img.min(), beta=rs_img.max(), norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_8U)
    return rs_i
```

**Comment by ShunyuanZheng** [comment]
Thx!
