### ISSUE TITLE
关于0034_04的mask可能有一些问题

### ISSUE THREAD

**Issue by tlxhlll** [DNA-Rendering/DNA-Rendering#9]
0034_04，camera00，mask有些是没有对准的,以000028.jpg为例
<img width="548" alt="image" src="https://github.com/DNA-Rendering/DNA-Rendering/assets/51501042/e9697d41-2746-44d8-9d56-d86df10d9a9f">
<img width="550" alt="image" src="https://github.com/DNA-Rendering/DNA-Rendering/assets/51501042/00b50c9c-e07b-4937-8f63-473ea76f963a">
<img width="548" alt="image" src="https://github.com/DNA-Rendering/DNA-Rendering/assets/51501042/4dd39fe4-ae96-4100-8c79-a56b42931c0b">

**Comment by DNA-Rendering** [comment]
Hi @tlxhlll ,

Thank you for mentioning this issue. 

We're sorry about the matting offset problem, but we've already fixed it and uploaded to google drive recently, please check the example below. You can find the new version in "Part 1/dna_rendering_part1_annotations/0034_04.smc".

![vid_00 - frame at 0m1s](https://github.com/DNA-Rendering/DNA-Rendering/assets/136057575/d6d055e5-337e-4240-a5bc-6fac4cd81968)
